container:
  image: golang:1.13

env:
  GOPROXY: https://proxy.golang.org

test_task:
  test_script:
    - apt-get update
    #- apt-get install -y asciidoc docbook-utils docbook-xml libxml2-utils xsltproc
    - apt-get install -y tree
    - GOPATH=/tmp/go
    - mkdir -p $GOPATH/src/github.com/cea-hpc
    - mv /tmp/cirrus-ci-build $GOPATH/src/github.com/cea-hpc/sshproxy
    - cd $GOPATH/src/github.com/cea-hpc/sshproxy
    #- make
    - make get-deps
    - cd $GOPATH
    - tree
    - make check
    - make test
