container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

test_task:
  test_script:
    - GOPATH=/tmp/go
    - echo $GOPATH
    - mkdir -p /tmp/go/src/github.com/cea-hpc
    - mv /tmp/cirrus-ci-build /tmp/go/src/github.com/cea-hpc/sshproxy
    - cd /tmp/go/src/github.com/cea-hpc/sshproxy
    - make
    - make get-deps check
    - make test
