container:
  image: golang:1.13

env:
  GOPROXY: https://proxy.golang.org

test_task:
  test_script:
    - GOPATH=/tmp/go
    - mkdir -p $GOPATH/src/github.com/cea-hpc
    - mv /tmp/cirrus-ci-build $GOPATH/src/github.com/cea-hpc/sshproxy
    - cd $GOPATH/src/github.com/cea-hpc/sshproxy
    - make get-deps check
    - rehash || echo "bof"
    - make test
