dist: xenial

language: go

# disable shallow clone
git:
  depth: false

services:
  - docker

before_install:
  - sudo apt-get install -y asciidoc docbook-utils docbook-xml libxml2-utils xsltproc

go:
  - 1.11.x
  - 1.12.x

notifications:
  email: false

script: make && make test
