os: linux

dist: focal

language: go

# disable shallow clone
git:
  depth: false

services:
  - docker

before_install:
  - sudo apt-get install -y asciidoc docbook-utils docbook-xml libxml2-utils xsltproc

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x

notifications:
  email: false

script:
  - make
  - make get-deps check
  - make test
