dist: xenial

language: go

# disable shallow clone
git:
  depth: false

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - docker version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose version

matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

notifications:
  email: false

script: make exe && make test
