dist: xenial

language: go

# disable shallow clone
git:
  depth: false

services:
  - docker

before_install:
  - sudo apt-get install -y asciidoc docbook-utils docbook-xml libxml2-utils xsltproc

matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

notifications:
  email: false

script: make && make test
