---
# Debug mode
#debug: false

# Where logs will be written.
# Default is empty but it can either be "syslog" if you want to use syslog or a
# filename where the pattern '{user}' which will be replaced by the user login
# (e.g. "/var/log/sshproxy/{user}.log").
#log: ""

# Minimum interval for checking if an host is alive.
# Empty by default (i.e. always check host).
# The string can contain a unit suffix such as 'h', 'm' and 's' (e.g. "2m30s").
#check_interval: ""

# Where raw dumps are written.
# Default is empty.
# It can be a path which can (and should) contain one or more of the following
# patterns:
#   - '{user}' replaced by the user login
#   - '{sid}' replaced by the unique session id
#   - '{time}' replaced by the connection starting time (e.g.
#     "2006-01-02T15:04:05.999999999Z07:00").
# The subdirectories will be created if needed.
# For example: "/var/lib/sshproxy/dumps/{user}/{time}-{sid}.dump"
# It can also be a network address where to send dumps if specified as
# 'TCP:host:port' (the TCP is case sensitive), e.g. 'TCP:collector:5555'.
#dump: ""

# Interval at which basic statistics of transferred bytes are logged.
# Empty by default, the string can contain a unit suffix such as 'h', 'm' and
# 's' (e.g. "2m30s"). These statistics are only available for non-interactive
# sessions or when the 'dump' option is set.
#stats_interval: ""

# A command can be launched in the background for the session duration.
# The standard and error outputs are only logged in debug mode.
#bg_command: ""

# etcd configuration. Associative array whose keys are:
# - endpoints: a list of etcd endpoints. Default is determined by the
#   underlying library.
# - tls: TLS configuration if enabled on etcd endpoints. Default is no TLS.
# - username: username if basic authentication is enabled.
# - password: password if basic authentication is enabled.
#etcd:
#    endpoints:
#        - "host1:port1"
#        - "host2:port2"
#    tls:
#        cafile: ""
#        keyfile: ""
#        certfile: ""
#    username: ""
#    password: ""

# How the host destination will be chosen. It can be "ordered" (the default) or
# "random". If "ordered", the hosts are tried in the order listed until a
# successful connection is made. The list is first randomly sorted if "random"
# is specified (i.e. a poor-man load-balancing algorithm).
#route_select: ordered

# Environment.
# Environment variables can be set if needed. The '{user}' pattern will be
# replaced with the user login.
#environment:
#    XAUTHORITY: /tmp/.Xauthority_{user}

# Global SSH options.
#ssh:
#    exe: ssh
#    args: ["-q", "-Y"]

# Routes definition.
# The key is the IP address or DNS name of the listening SSH daemon (with an
# optional port) and the value is an array of destination hosts (with an
# optional port). If a DNS name is used and resolves to several IP addresses,
# sshproxy will create the same route for each IP address. The special key
# "default" can be used to define a default route. The hosts are tried in the
# order specified in the previously defined "route_select" option.
#routes:
#    192.168.0.1: [host1, host2]
#    192.168.0.2: [host3, host4]
#    default: ["host5:4222"]

# Each option can be overridden for a Unix group of users.
# If a user is in multiple groups and these groups are defined in the
# configuration, the configuration of a previous group will be overridden by the
# next ones.
# The parameters defined in a "users" option (see below) will be applied last
# and override groups parameters.
#groups:
#    foo:
#        debug: true
#        log: /tmp/sshproxy-foo/{user}.log
#        # An associative array is used to specify environment, SSH options or
#        # routes.
#        environment:
#            ENV1: /tmp/env
#        ssh:
#            args: ["-vvv", "-Y"]
#        # If routes are specified, they are fully overridden, not merged.
#        routes:
#            default: [hostx]

# Each option can also be overridden for a specific user (eg. for debugging
# purpose).
#users:
#    foo:
#        debug: true
#        log: /tmp/sshproxy-{user}.log
#        dump: /tmp/sshproxy-{user}-{time}.dump
#        # An associative array is used to specify environment, SSH options or
#        # routes.
#        ssh:
#            args: ["-vvv", "-Y"]
